version: '3'
services:
  dick_richardson_mysql:
    image: mysql:5.7
    container_name: dick_richardson_mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: dick_richardson
    ports:
      - 127.0.0.1:$DICK_RICHARDSON_MYSQL_PORT:3306

  #################### Base  ####################

  base: &base
    image: darthjee/dick_richardson
    volumes:
      - ./source:/home/app/app
    links:
      - dick_richardson_mysql:mysql
    env_file: .env


  base_build:
    <<: *base
    build:
      context: .
      dockerfile: Dockerfile.dick_richardson
    command: echo done

  production_base_build:
    image: darthjee/production_dick_richardson
    env_file: .env
    environment:
      RAILS_ENV: production
    build:
      context: .
      dockerfile: Dockerfile.production_dick_richardson
    links:
      - dick_richardson_mysql:mysql
    command: echo done
  #################### CONTAINERS ####################

  dick_richardson_app:
    <<: *base
    container_name: dick_richardson_app
    command: /bin/bash bin/server.sh
    depends_on: [base_build]
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - RAILS_ENV=development
      - DICK_RICHARDSON_MYSQL_PORT=3306

  dick_richardson_tests:
    <<: *base
    container_name: dick_richardson_tests
    command: /bin/bash bin/tests.sh
    depends_on: [base_build]
    environment:
      - RAILS_ENV=test

  dick_richardson_root:
    <<: *base
    user: root
    container_name: dick_richardson_root
    command: /bin/bash
    depends_on: [base_build]
  dick_richardson_production:
    env_file: .env.production
    container_name: dick_richardson_production
    image: $PRODUCTION_IMAGE
