FROM darthjee/dick_richardson-base:0.0.3

WORKDIR /home/app/app
COPY --chown=app:app source/Gemfile* /home/app/app/
COPY --chown=app:app source/bower.json /home/app/app/

RUN bundle install --clean

USER app
RUN bower install
