version: '2'
services:
  base: &base
    build: .
    working_dir: /home/app/urna
    volumes:
      - .:/home/app/urna
      - urna_gems_2_4_0:/usr/local/bundle

  #################### CONTAINERS ####################

  urna:
    <<: *base
    container_name: urna
    command: bash -c 'gem install bundler; bundle install; /bin/bash'

volumes:
  urna_gems_2_4_0:
