version: '2'
services:
  urna_postgres:
    image: postgres:9.5
    container_name: urna_postgres
    env_file: .env
    environment:
      POSTGRES_USER: urna
      POSTGRES_PASSWORD: urna
    ports:
      - 127.0.0.1:$URNA_POSTGRES_PORT:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  #################### Base  ####################

  base: &base
    build: .
    env_file: .env
    links:
      - urna_postgres:postgres
    volumes:
      - .:/home/app/urna
      - urna_gems_2_4_0:/usr/local/bundle

  #################### CONTAINERS ####################

  urna_app:
    <<: *base
    container_name: urna_app
    command: /bin/bash bin/server.sh
    ports:
      - 0.0.0.0:3000:3000
    environment:
      - RAILS_ENV=development
      - URNA_POSTGRES_PORT=5432

  urna_tests:
    <<: *base
    container_name: urna_tests
    command: /bin/bash bin/tests.sh
    environment:
      - RAILS_ENV=test

  urna_root:
    <<: *base
    user: root
    container_name: urna_root
    command: /bin/bash

networks:
  default:
    external:
      name: urna

volumes:
  urna_gems_2_4_0:
  postgres_db:
