version: 2
workflows:
  version: 2
  test-and-release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - checks:
          filters:
            tags:
              only: /.*/
      - test-build:
          requires: [test, checks]
          filters:
            tags:
              only: /.*/
      - build-and-release:
          requires: [test, checks]
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
jobs:
  test:
    docker:
      - image: darthjee/circleci_dick_richardson-base:0.0.3
        environment:
          DICK_RICHARDSON_MYSQL_HOST: mysql
          DICK_RICHARDSON_MYSQL_PORT: 3306
          DICK_RICHARDSON_MYSQL_USER: dick_richardson
          DICK_RICHARDSON_MYSQL_NAME: dick_richardson
          DICK_RICHARDSON_MYSQL_PASSWORD: dick_richardson
          DICK_RICHARDSON_PASSWORD_SALT: abcd
          DICK_RICHARDSON_REDIS_URL: redis://redis:6379/0
      - image: circleci/redis:latest
        name: redis
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: dick_richardson_test
          MYSQL_USER: dick_richardson
          MYSQL_PASSWORD: dick_richardson
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Prepare Coverage Test Report
          command: cc-test-reporter before-build
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Bower Install
          command: bundle exec rake bower:install
      - run:
          name: Wait for database
          command: scripts/wait_for_db.sh
      - run:
          name: Migrate
          command: RAILS_ENV=test bundle exec rake db:schema:load
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Coverage Test Report
          command: cc-test-reporter after-build --exit-code $?

  checks:
    docker:
      - image: darthjee/circleci_dick_richardson-base:0.0.3
        environment:
          DICK_RICHARDSON_MYSQL_HOST: mysql
          DICK_RICHARDSON_MYSQL_PORT: 3306
          DICK_RICHARDSON_MYSQL_USER: dick_richardson
          DICK_RICHARDSON_MYSQL_NAME: dick_richardson
          DICK_RICHARDSON_MYSQL_PASSWORD: dick_richardson
          DICK_RICHARDSON_PASSWORD_SALT: abcd
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: dick_richardson_test
          MYSQL_USER: dick_richardson
          MYSQL_PASSWORD: dick_richardson
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Rubocop
          command: rubocop
  test-build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/deploy.sh build
  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Trigger Deploy
          command: scripts/deploy.sh deploy
